quarkus:
  application:
    name: reactiveApp
  http:
    port: ${SERVER_PORT}
  log:
    level: "INFO"
    console:
      enable: true
instance-of-me:
  servers:
  - http://localhost:4070
  - http://localhost:4080
  - http://localhost:4090
  schedule: "10s"

